name: stream-flix-player # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: StreamFlix Media
summary: Watch videos from local or online sources.
description: A sleek multimedia player supporting major formats and streaming protocols. Create playlists, adjust subtitles, and enjoy seamless playback.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  stream-flix-player:
    command: bin/stream-flix-player-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  stream-flix-player:
    plugin: dump
    source: .
    organize:
      stream-flix-player-bin: bin/
